config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :posts
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'posts#index'

  namespace 'api' do
    namespace 'v1' do
      resources :uwactivestorage#index
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :feature_image


  #https://stackoverflow.com/questions/50640231/active-storage-with-amazon-s3-not-saving-with-filename-specified-but-using-file#:~:text=In%20order%20to%20have%20a%20custom%20filename%20on%20S3
  
  #def url()
  #  return "https://placehold.it/#{size}" unless feature_image.attached?
  #
  #  'https://my_s3_subdomain.amazonaws.com/' +
  #      feature_image.variant(resize: SIZES[size]).processed.key
  #end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/uwactivestorage_controller.rb
module Api
  module V1
    
    #class UwactivestorageController < ApplicationController
    class UwactivestorageController < ActiveStorage::DirectUploadsController

      protect_from_forgery with: :exception
      skip_before_action :verify_authenticity_token
      #before_action :doorkeeper_authorize! # this is doorkeeper specific, but you can use any token authentication scheme here

      def index
        signedid = 'No data available'
        render json: {status: 'SUCCESS', message: 'TestOnly', signed_id: signedid }, status: :ok
      end
      
      def create

        # Step 5.1: Get the parameter data from the frontend
        pfilename = params[:public_id] #params[:filename]
        pchecksum = params[:checksum]
        pbytesize = params[:byte_size]
        pcontenttype = params[:content_type]
        ppublicid  = params[:public_id]
 
        # Step 5.2: Create the Blob object that includes the signed_id
        blob = ActiveStorage::Blob.create_before_direct_upload!(          
          filename: pfilename, 
          byte_size: pbytesize, 
          checksum: pchecksum, 
          content_type: pcontenttype
        )
 
        #Step 5.3: Prepare the information needed in the frontend to perform the updating of the asset public_id in the Media Library using the Blob.key as the filename

        # PLEASE PROTECT THIS SECTION
        cldCloudName = "ecpdemo"
        cldApiKey = "487125246667464"
        cldApiSecretKey = "BpR0LBWVJ3yA7xt9uPggHIECq_k"        
        cldRenameURL = "https://api.cloudinary.com/v1_1/" + cldCloudName + "/image/rename"
        cldBAParams = "Basic " + (Base64.encode64(cldApiKey + ":" + cldApiSecretKey)).tr("\n", '')
        # PLEASE PROTECT THIS SECTION

        unixTimestamp = Time.now.to_i

        cldRenameParams = "from_public_id="
        cldRenameParams.concat(ppublicid)
        cldRenameParams.concat("&timestamp=")
        cldRenameParams.concat(unixTimestamp.to_s)
        cldRenameParams.concat("&to_public_id=")
        cldRenameParams.concat(blob.key)
        cldRenameParams.concat(cldApiSecretKey)
        calcSignature = Digest::SHA1.hexdigest(cldRenameParams)

        # Step 5.4: Return the calculated data back to the frontend to continue the Step 6
        render json: {
          status: 'SUCCESS', 
          message: 'Blob', 
          signed_id: blob.signed_id, 
          blob_key: blob.key,
          cldrenameurl: cldRenameURL,
          baparams: cldBAParams, 
          cldfrompublicid: pfilename,
          cldtopublicid: blob.key,
          cldtimestamp: unixTimestamp,
          cldapikey: cldApiKey,
          cldsignature: calcSignature,
          cldtrenameparams: cldRenameParams,
          blobdata: blob
          }, status: :ok

      end

      # Rescue the Auth Error
      def not_authorized
        render json: { error: 'Not authorized' }, status: :unauthorized
      end


      private

        def uwactivestorage_params
          params.permit(:filename, :byte_size, :checksum, :content_type, :public_id)
        end

        def blob_args
          params.require(:blob).permit(:filename, :byte_size, :checksum, :content_type).to_h.symbolize_keys
        end

        def verified_service_name
          ActiveStorage::DirectUploadToken.verify_direct_upload_token(params[:direct_upload_token], params[:attachment_name], session)
        end

        def direct_upload_json(blob)
          blob.as_json(root: false, methods: :signed_id).merge(direct_upload: {
            url: blob.service_url_for_direct_upload,
            headers: blob.service_headers_for_direct_upload
          })
        end



    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_post, only: [:show, :edit, :update, :destroy]


  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    
    #@post.feature_image = "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBRUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--754ba2022f3577e0e87ec8b99dc65b3d39788f52"

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.'}
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body, :user_id, :feature_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<h1 class="semibold text-2xl">Welcome to Kickoff!</h1>
<p class="lead">Use this starting point as a way to quickly set up a new project by generating files, installing gems, and more.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kickoff</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag  'application', 'data-turbolinks-track': 'reload' %>

  </head>

 <body class="bg-white">

  <% flash.each do |type, message| %>
    <% if type == "alert" %>
      <div class="bg-red-500">
        <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= message %></div>
      </div>
    <% end %>
    <% if type == "notice" %>
      <div class="bg-green-500">
        <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= message %></div>
      </div>
    <% end %>
  <% end %>

    <header class="mb-4">
      <nav class="flex items-center justify-between flex-wrap bg-gray-100 py-3 lg:px-10 px-3 text-gray-700 border-b border-gray-400">
        <div class="flex items-center flex-no-shrink mr-6">
          <%= link_to "Kickoff", root_path, class:"link text-xl tracking-tight font-semibold" %>
        </div>
        <div class="block lg:hidden">
          <button class="flex items-center px-3 py-2 border rounded text-grey border-gray-500 hover:text-gray-600 hover:border-gray-600">
            <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
          </button>
        </div>
        <div class="w-full block lg:flex-1 lg:flex items-center text-center lg:text-left">
          <div class="lg:flex-grow">
            <%= link_to "Basic Link", "#", class: "block mt-4 lg:inline-block lg:mt-0 lg:mr-4 mb-2 lg:mb-0 link" %>
          </div>
          <div class="w-full block lg:flex lg:flex-row lg:flex-1 mt-2 lg:mt-0 text-center lg:text-left lg:justify-end items-center">
            <% if user_signed_in? %>
             <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"btn btn-default mb-2 lg:mr-2 lg:mb-0 block" %>
            <% else %>
              <%= link_to "Login", new_user_session_path, class:"btn btn-default mb-2 lg:mr-2 lg:mb-0 block" %>
            <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-default block" %>
            <% end %>
          </div>
        </div>
      </nav>
    </header>

    <main class="lg:px-10 px-4">
      <%= content_for?(:content) ? yield(:content) : yield %>
    </main>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true, multipart: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-6">
    <%= form.label :title, class: "label" %>
    <%= form.text_field :title, class: "input" %>
  </div>

  <div class="mb-6">
    <%= form.label :body, class: "label" %>
    <%= form.text_area :body, class: "input" %>
  </div>

  <div class="mb-6">
    <%= form.label :feature_image, class: "label" %>
    <div class="dropzone dropzone-default dz-clickable" data-controller="dropzone" data-dropzone-max-file-size="2" data-dropzone-max-files="1">
    <%= form.file_field :feature_image, direct_upload: true, data: { target: 'dropzone.input' } %>
    <div class="dropzone-msg dz-message needsclick text-gray-600">
      <h3 class="dropzone-msg-title">Drag here to upload or click here to browse</h3>
      <span class="dropzone-msg-desc text-sm">2 MB file size maximum. Allowed file types png, jpg.</span>
      </div>
    </div>
  </div>

  <div class="mb-6">
    <%= form.submit  class: "btn-default btn" %>
  </div>



  <br/>
  <hr/>
  <h4>Test on upload widget </h4>
  
  <div id="widgetdiv"></div>
  <div id="uwdiv"> 
    <form ="uwform"></form>   
  </div>
  <script src="https://upload-widget.cloudinary.com/global/all.js" type="text/javascript"></script>
    
  <%= javascript_pack_tag 'uwactivestorage' %>


<% end %>

app/views/posts/edit.html.erb
<div class="max-w-2xl m-auto">
  <h1 class="text-3xl font-bold text-black mb-6">Edit Post</h1>

  <%= render 'form', post: @post %>
</div>

app/views/posts/index.html.erb
<div class="xmax-w-6xl m-auto">
  <div class="flex items-center justify-between pb-4 mb-4 border-b">
    <h1 class="text-xl font-bold mb-0 uppercase text-gray-500">Posts</h1>
    <%= link_to "New Post", new_post_path, class: "btn btn-default" if user_signed_in? %>
  </div>

  <div class="flex flex-wrap items-center justify-between">
  <% @posts.each do |post| %>
    <article class="border rounded-lg lg:w-1/3 w-full">
      <%= link_to post do %>
        <%= image_tag post.feature_image if post.feature_image.present? %>
      <% end %>

      <div class="p-6">
        <h1 class="text-2xl font-bold"><%= link_to post.title, post %></h1>

        <div class="leading-normal text-lg">
          <%= post.body %>
        </div>

        <% if user_signed_in? && current_user.id == post.user_id %>
          <div class="my-4">
            <%= link_to 'Edit', edit_post_path(post), class: "btn btn-default" %>
            <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
          </div>
        <% end %>
      </div>
    </article>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="xmax-w-2xl m-auto">
  <h1 class="text-3xl font-bold text-black mb-6">New Post</h1>

  <%= render 'form', post: @post %>
</div>

app/views/posts/show.html.erb
<div class="max-w-4xl m-auto">
  <%= link_to @post do %>
    <%= image_tag @post.feature_image if @post.feature_image.present? %>
  <% end %>

  <div class="p-6">
    <h1 class="text-2xl font-bold"><%= @post.title %></h1>

    <div class="leading-normal text-lg">
      <%= @post.body %>
    </div>

    <% if user_signed_in? && current_user.id == @post.user_id %>
      <div class="my-4">
        <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-default" %>
        <%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
    </div>
    <% end %>
  </div>
</div>